#==============================================================
# Debug mode
#==============================================================
localhost: http://localhost:3000
# debug : true
debug : false


#==============================================================
# Maintain mode
#==============================================================
# maintain : true
maintain : false


#==============================================================
# Administator info
#==============================================================
admin_name: Houth
admin_email: hello@houth.tw


#==============================================================
# Site settings
#==============================================================
site_name         : Houth
site_title        : Houth
site_description  : 網站描述
site_url          : https://houth.tw
site_version      : 1.0.0
og_type           : website
og_image          : https://houth.tw/images/fb.jpg
ga_track_id       : UA-XXXXXXXX-XX


#==============================================================
# Facebook APP
#==============================================================
fb_app_id: XXXXXXXXXXXXXXXX
fb_app_version: v2.5


#==============================================================
# Jekyll config
#==============================================================
permalink: /portfolio/:slug/


#==============================================================
# CloudCannon config
#==============================================================
_options:
  image:
    uploads_dir: "uploads/:title"
  content:
    format: div p h1 h2 h3 h4 h5 h6
    bold: true
    italic: true
    numberedlist: true
    bulletedlist: true
    image: true
    table: true
    embed: true
    removeformat: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    blockquote: true
    horizontalrule: true
    left: text-left
    right: text-right
    center: text-center


#==============================================================
# Build exclude
#==============================================================
exclude:
  - gulpfile.js
  - package.json
  - node_modules
  - assets


#==============================================================
# Html compress config
#==============================================================
compress_html:
  clippings: all

